name: Build & Deploy

on:
  push:
    branches:
      [main, master]

jobs:
  push_compose:
    name: Push docker-compose.yaml to remote server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy docker-compose.yaml via SSH
        uses: appleboy/scp-action@master
        with:
          host: 194.87.237.176
          username: ${{ secrets.SSH_USER }}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: 22
          source: "docker-compose.yml"
          target: "/home/${{ secrets.SSH_USER }}"
          overwrite: true

  build_and_push_images:
    name: Push image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Review Bot Build and Push to Dockerhub
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tkk-bot-app

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [ build_and_push_images, push_compose ]
    steps:
      - name: Connect with SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 194.87.237.176
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo DB_USER = ${{ secrets.DB_USER }} >> tkk-bot-app-env.txt
            echo DB_PASS = ${{ secrets.DB_PASS }} >> tkk-bot-app-env.txt
            echo SSH_USER = ${{ secrets.SSH_USER }} >> tkk-bot-app-env.txt
            echo BOT_TOKEN = ${{ secrets.BOT_TOKEN }} >> tkk-bot-app-env.txt
            echo BOT_NAME = ${{ secrets.BOT_NAME }} >> tkk-bot-app-env.txt
            echo WEB_PASS = ${{ secrets.WEB_PASS }} >> tkk-bot-app-env.txt
            
            sudo docker stop tkk-bot-app
            sudo docker rm tkk-bot-app
            sudo docker rmi l2ilai/tkk-bot-app
            sudo docker-compose -f docker-compose.yml --env-file=tkk-bot-app-env.txt up -d
            sudo rm tkk-bot-app-env.txt
            
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
            sudo docker cp id_rsa tkk-bot-app:/home/id_rsa
            sudo rm id_rsa
